name: Build, Publish NuGet, and Create Release
 
on:
    workflow_dispatch:
    push:
        branches:
        - develop
        - master
        
concurrency:
    group: "${{ github.event.repository.name }}_group"
    cancel-in-progress: false

jobs:
    BuildTestAndPublish:
        uses: NashefSystems/NS.DevOps.Files/.github/workflows/Nuget_CI-CD.yml@master
        secrets: inherit
